namespace: static

deployment:
  name: blog
  image: ghcr.io/torbencarstens/blog:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  ports:
  - 8080
  labels:
    app: blog
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

configmap:
  nginx:
    name: blog

service:
  name: blog
  port: 80
  targetPort: 8080
  appSelector: blog

ingress:
  hosts:
    - blog.carstens.tech
  secret: tls-blog
  issuer: letsencrypt-issuer
  name: blog
